#!/usr/bin/env zsh

if [[ -z $STOW_FOLDERS ]]; then
    # Use find to list non-hidden subdirectories in the current working directory
    STOW_FOLDERS=$(find . -maxdepth 1 -type d -not -name ".*" -printf "%f," | sed 's/,$//')
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/.dotfiles
fi

STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES $DOTFILES/install

